version: "2.4"
services:
  autoheal:
    restart: always
    image: cryi/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - COMPOSE_MODE=true
      - AUTOHEAL_DELAY=60
      - AUTOHEAL_INTERVAL=5
      - STOP_TIMEOUT=120
    logging:
      options:
        max-size: '5m'
        max-file: '1'
      driver: json-file

  ip-map:
    restart: always
    init: true
    build: ./containers/ip-map
    stop_grace_period: 2m
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:       
      - "./.icc/etho:/etho:ro"
      - "./.icc/ip-map:/ip-map:rw"
    logging:
      options:
        max-size: '5m'
        max-file: '1'
      driver: json-file

  mn:
    restart: always
    init: true
    build: ./containers/etho
    stop_grace_period: 2m
    volumes:
      - "./data/etho:/home/etho/.ether1:rw"
      - "./.icc/etho:/etho:rw"
      - "./.icc/ip-map:/ip-map:ro"
    pids_limit: 100
    labels:
      - autoheal=true
    ports:
      - "30305:30305"
      - "30305:30305/udp"
    env_file:
      - "./.env"
    logging:
      options:
        max-size: '10m'
        max-file: '4'
      driver: json-file
