version: "2.4"
services:
  gethexporter:
    restart: always
    init: true
    image: hunterlong/gethexporter
    stop_grace_period: 2m
    labels:
      - autoheal=true
    ports:
      - "9090:9090"
    environment:
      - GETH=http://mn:8545
      - DELAY=1000
